-- subscribe_balance_check_log — per-user balance check outcomes at subscription
-- time. Append-only. 90-day retention then archive/purge (operational, not audit).
-- Rate-limited in application code: max 3 attempts per user per 60 seconds.
-- Columns spec'd in PRD v3.3 §12.
--
-- IMPORTANT: never expose balance_usd_equivalent or fx_rate_used in user-facing
-- output. The internal $90/$85 thresholds (per PRD §7) must not appear in any
-- error message visible to the user — only "we recommend at least $100 USD
-- equivalent" is permissible. This is a write-only-for-server table.

create table public.subscribe_balance_check_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  hfm_account_number text not null,
  balance_account_currency numeric not null,
  account_currency text not null,
  balance_usd_equivalent numeric not null,
  fx_rate_used numeric not null,
  passed boolean not null,
  reason_if_failed text,
  checked_at timestamptz not null default now()
);

create index subscribe_balance_check_log_user_id_idx
  on public.subscribe_balance_check_log (user_id, checked_at desc);

-- append-only enforcement (blocks every role, including service_role)
create trigger subscribe_balance_check_log_no_update
  before update on public.subscribe_balance_check_log
  for each statement execute function public.raise_append_only();
create trigger subscribe_balance_check_log_no_delete
  before delete on public.subscribe_balance_check_log
  for each statement execute function public.raise_append_only();

alter table public.subscribe_balance_check_log enable row level security;
-- RLS enabled with no policies. service_role bypasses RLS, all other roles get
-- zero rows by default. This is intentional for service-role-only tables.
