-- market_news_cache — Claude Haiku per-pair sentiment summaries. input_hash
-- dedupes regenerations from the same headline set. Cached for the duration
-- in expires_at (typically 30-60 minutes).

create table public.market_news_cache (
  id bigint generated by default as identity primary key,
  pair pair not null,
  bias news_bias not null,
  summary text not null,                             -- 2-3 sentences
  input_hash text not null,                          -- sha256 of input headlines
  generated_at timestamptz not null default now(),
  expires_at timestamptz not null,
  unique (pair, input_hash)
);

create index market_news_cache_active_idx
  on public.market_news_cache (pair, expires_at desc);

alter table public.market_news_cache enable row level security;

create policy "market_news_cache read auth+disclosure"
  on public.market_news_cache for select
  to authenticated
  using (public.has_signed_disclosure());
