-- news_headlines — raw headlines from Finnhub or other providers. Powers the
-- market_news_cache generator and admin debugging.

create table public.news_headlines (
  id bigint generated by default as identity primary key,
  source text not null,                              -- finnhub | trading_economics | manual
  symbol text,                                       -- pair (EUR/USD) or currency code (USD)
  headline text not null,
  url text,
  published_at timestamptz,
  ingested_at timestamptz not null default now(),
  raw jsonb
);

create index news_headlines_published_at_idx
  on public.news_headlines (published_at desc);
create index news_headlines_symbol_idx
  on public.news_headlines (symbol, published_at desc);

alter table public.news_headlines enable row level security;

create policy "news_headlines read auth+disclosure"
  on public.news_headlines for select
  to authenticated
  using (public.has_signed_disclosure());
