-- notification_log — outbound notifications with dedupe via dedupe_key.
-- Useful for: avoiding duplicate signal alerts, tracking delivery, debugging.

create table public.notification_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel notification_channel not null,
  type text not null,                                -- signal_fired | daily_digest | balance_check_failed | etc.
  subject text,
  body text,
  dedupe_key text not null unique,                   -- e.g. user_id:signal_id:type
  sent_at timestamptz not null default now(),
  delivery_status delivery_status not null default 'sent',
  error text
);

create index notification_log_user_id_idx
  on public.notification_log (user_id, sent_at desc);

alter table public.notification_log enable row level security;

create policy "notification_log select own"
  on public.notification_log for select
  to authenticated
  using (user_id = auth.uid());
