-- admin_action_log — append-only audit trail. Per CLAUDE.md, every destructive
-- admin action calls logAdminAction() BEFORE executing (step 4). The handler
-- then UPDATEs after_state once the action completes (step 6).
--
-- "Append-only" here means:
--   - DELETE blocked for all roles, including service_role
--   - UPDATE blocked for all roles EXCEPT setting after_state from null -> non-null
--   - Once after_state is set, the row is fully immutable
--
-- This nuance is necessary to support the documented admin-action pattern.

create table public.admin_action_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references public.admin_users(user_id) on delete restrict,
  action_type text not null,                         -- pause_master | close_master_position | mark_user_subscribed | ...
  target_type text,                                  -- master_account | user | system
  target_id text,                                    -- uuid string or 'global'
  before_state jsonb,
  after_state jsonb,                                 -- updated once by handler post-action
  reason_note text,
  ip inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index admin_action_log_created_at_idx on public.admin_action_log (created_at desc);
create index admin_action_log_admin_user_idx
  on public.admin_action_log (admin_user_id, created_at desc);
create index admin_action_log_target_idx on public.admin_action_log (target_type, target_id);

-- DELETE always blocked
create trigger admin_action_log_no_delete
  before delete on public.admin_action_log
  for each statement execute function public.raise_append_only();

-- UPDATE: row-level check that only after_state changed and was previously null
create or replace function public.admin_action_log_after_state_only()
returns trigger
language plpgsql
as $$
begin
  if old.id is distinct from new.id
    or old.admin_user_id is distinct from new.admin_user_id
    or old.action_type is distinct from new.action_type
    or old.target_type is distinct from new.target_type
    or old.target_id is distinct from new.target_id
    or old.before_state is distinct from new.before_state
    or old.reason_note is distinct from new.reason_note
    or old.ip is distinct from new.ip
    or old.user_agent is distinct from new.user_agent
    or old.created_at is distinct from new.created_at
  then
    raise exception 'admin_action_log: only after_state may be modified post-insert'
      using errcode = 'P0001';
  end if;
  if old.after_state is not null then
    raise exception 'admin_action_log: after_state already set, row is immutable'
      using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger admin_action_log_after_state_only_trigger
  before update on public.admin_action_log
  for each row execute function public.admin_action_log_after_state_only();

alter table public.admin_action_log enable row level security;
-- RLS enabled with no policies. service_role bypasses RLS, all other roles get
-- zero rows by default. This is intentional for service-role-only tables.
