-- signal_confluence_factors — per-factor breakdown for each signal in the
-- signals table. Seven rows per signal in the typical case (one per factor).

create table public.signal_confluence_factors (
  id bigint generated by default as identity primary key,
  signal_id uuid not null references public.signals(id) on delete cascade,
  factor_number smallint not null check (factor_number between 1 and 7),
  factor_name text not null,
  awarded boolean not null,
  reason text,                                       -- "PDL swept at 1.0820" or "OB mitigated 12 min before CHoCH"
  created_at timestamptz not null default now(),
  unique (signal_id, factor_number)
);

create index signal_confluence_factors_signal_id_idx
  on public.signal_confluence_factors (signal_id);

alter table public.signal_confluence_factors enable row level security;

create policy "signal_confluence_factors read auth+disclosure"
  on public.signal_confluence_factors for select
  to authenticated
  using (public.has_signed_disclosure());
