-- economic_calendar_cache — upcoming red-folder events per currency. Polled
-- from Trading Economics every 15 minutes. Drives Filter 2 (calendar blackout)
-- in the signal engine.

create table public.economic_calendar_cache (
  id bigint generated by default as identity primary key,
  external_id text unique,                           -- Trading Economics event id
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  event_name text not null,
  importance event_importance not null,              -- 'high' = red folder
  scheduled_at timestamptz not null,
  forecast text,
  previous text,
  actual text,
  ingested_at timestamptz not null default now()
);

create index economic_calendar_cache_scheduled_at_idx
  on public.economic_calendar_cache (scheduled_at);
create index economic_calendar_cache_currency_idx
  on public.economic_calendar_cache (currency, scheduled_at);

alter table public.economic_calendar_cache enable row level security;

create policy "economic_calendar_cache read auth+disclosure"
  on public.economic_calendar_cache for select
  to authenticated
  using (public.has_signed_disclosure());
