-- master_account_metrics — periodic equity/balance snapshots powering the
-- public equity curve on the dashboard. Captured by the bot worker (or
-- master sync edge function) at a fixed cadence (e.g. hourly).

create table public.master_account_metrics (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  equity numeric not null,
  balance numeric not null,
  floating_pnl numeric not null default 0,
  open_positions_count smallint not null default 0,
  source text not null default 'metaapi'             -- metaapi | manual | hfm_api
);

create index master_account_metrics_captured_at_idx
  on public.master_account_metrics (captured_at desc);

alter table public.master_account_metrics enable row level security;

create policy "master_account_metrics read auth+disclosure"
  on public.master_account_metrics for select
  to authenticated
  using (public.has_signed_disclosure());
