-- signal_evaluations — forensic audit log of every M15 evaluation, regardless
-- of score. Append-only. 90-day retention then archive/purge (operational, not
-- compliance). ~216 rows/day across 9 pairs during active sessions.
-- Same append-only pattern as subscribe_balance_check_log and admin_action_log.

create table public.signal_evaluations (
  id bigint generated by default as identity primary key,
  pair pair not null,
  direction direction,                              -- nullable: bias may be ranging
  evaluated_at timestamptz not null default now(),
  htf_d1_bias htf_bias,
  htf_h4_bias htf_bias,
  passed_htf_bias boolean not null default false,
  sweep_detected boolean not null default false,
  choch_detected boolean not null default false,
  reached_scoring boolean not null default false,
  confluence_score smallint check (confluence_score between 0 and 7),
  classification signal_classification,
  discard_reason text,
  details jsonb,                                     -- full raw eval payload
  created_at timestamptz not null default now()
);

create index signal_evaluations_evaluated_at_idx
  on public.signal_evaluations (evaluated_at desc);
create index signal_evaluations_pair_idx
  on public.signal_evaluations (pair, evaluated_at desc);

-- append-only enforcement (blocks every role including service_role)
create trigger signal_evaluations_no_update
  before update on public.signal_evaluations
  for each statement execute function public.raise_append_only();
create trigger signal_evaluations_no_delete
  before delete on public.signal_evaluations
  for each statement execute function public.raise_append_only();

alter table public.signal_evaluations enable row level security;
-- RLS enabled with no policies. service_role bypasses RLS, all other roles get
-- zero rows by default. This is intentional for service-role-only tables.
